### ISSUE TITLE
Figure out .dev.wasm or not

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#356]
Right now we have `replicache.wasm` and `replicache.dev.wasm`. The dev version is made using `--profiling` but it seems like the files are identical:

```
~/src/repc  main ✗
▶ cksum pkg/release/replicache_client_bg.wasm
3885561882 748532 pkg/release/replicache_client_bg.wasm

~/src/repc  main ✗
▶ cksum pkg/debug/replicache_client_bg.wasm
3885561882 748532 pkg/debug/replicache_client_bg.wasm
```

**Comment by arv** [comment]
https://rustwasm.github.io/docs/wasm-pack/commands/build.html?highlight=profile#profile

**Comment by arv** [comment]
Maybe it is `wasm-opt` that stripping the symbols?

Let's remove the optimizations for the dev build!

**Comment by arv** [comment]
```
~/src/repc  main ✗
▶ ls -l pkg/release/replicache_client_bg.wasm*
-rw-r--r--  1 arv  staff  710979 Jun  3 15:41 pkg/release/replicache_client_bg.wasm
-rw-r--r--  1 arv  staff  193240 Jun  3 15:41 pkg/release/replicache_client_bg.wasm.br
-rw-r--r--  1 arv  staff     880 Jun  3 15:41 pkg/release/replicache_client_bg.wasm.d.ts

~/src/repc  main ✗
▶ ls -l pkg/debug/replicache_client_bg.wasm*
-rw-r--r--  1 arv  staff  829021 Jun  3 15:41 pkg/debug/replicache_client_bg.wasm
-rw-r--r--  1 arv  staff  210191 Jun  3 15:41 pkg/debug/replicache_client_bg.wasm.br
-rw-r--r--  1 arv  staff     880 Jun  3 15:41 pkg/debug/replicache_client_bg.wasm.d.ts
```

```
~/src/repc  main ✗
▶ cksum pkg/release/replicache_client_bg.wasm
563426312 710979 pkg/release/replicache_client_bg.wasm

~/src/repc  main ✗
▶ cksum pkg/debug/replicache_client_bg.wasm
149183458 829021 pkg/debug/replicache_client_bg.wasm
```

**Comment by arv** [comment]
I made a change to make `performance.now()` throw an exception. With `wasm-opt` I get:

```
Error: Intentional error
  at Object.p.now (src/replicache.test.ts:2069:12)
  at performanceNow (bin/repc/release/snippets/replicache-client-1d38ac1822bf91ef/src/util/wasm/mod.js:5:22)
  at http://localhost:8000/src/wasm/release/replicache_client_bg.wasm:wasm-function[118]:0x4e5a4
  at http://localhost:8000/src/wasm/release/replicache_client_bg.wasm:wasm-function[336]:0x8c6a6
  at _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hfaaf31433937b041 (http://localhost:8000/src/wasm/release/replicache_client_bg.wasm:wasm-function[742]:0xa1328)
  at __wbg_adapter_35 (bin/repc/release/replicache_client.js:220:10)
  at real (bin/repc/release/replicache_client.js:201:20)
```

and without `wasm-opt` I get:

```
Error: Intentional error
  at Object.p.now (src/replicache.test.ts:2069:12)
  at performanceNow (bin/repc/debug/snippets/replicache-client-1d38ac1822bf91ef/src/util/wasm/mod.js:5:22)
  at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h74a2ab28f60f0195 (http://localhost:8000/src/wasm/debug/replicache_client_bg.wasm:wasm-function[118]:0x52c42)
  at wasm_bindgen_futures::queue::Queue::new::{{closure}}::heede5b13f4287ca9 (http://localhost:8000/src/wasm/debug/replicache_client_bg.wasm:wasm-function[343]:0x95573)
  at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfaaf31433937b041 (http://localhost:8000/src/wasm/debug/replicache_client_bg.wasm:wasm-function[766]:0xab694)
  at __wbg_adapter_35 (bin/repc/debug/replicache_client.js:220:10)
  at real (bin/repc/debug/replicache_client.js:201:20)
```

So with this we do get some symbols

**Comment by aboodman** [comment]
Fantastic. Let's do it.
