### ISSUE TITLE
Flaky test in Firefox and WebKit onSync {useMemstore: false} 

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#360]
```
 ❌ onSync {useMemstore: false} (failed on Firefox)
      AssertionError: expected 6 to equal 2
      + expected - actual
      
      -6
      +2
      
      at r (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:9574:12)
      at n.exports<[3]</t.exports/i.prototype.assert (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:250:12)
      at p (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:1409:11)
      at c (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:7884:24)
      at src/replicache.test.ts:1576:30
      at async*testWithBothStores/< (src/replicache.test.ts:134:14)
```

- https://github.com/rocicorp/replicache/runs/2338100194#step:9:30
- https://github.com/rocicorp/replicache/runs/2262296046#step:9:169

**Comment by arv** [comment]
Also flaky on webkit

```
  ❌ onSync {useMemstore: false} (failed on Webkit)
      AssertionError: expected 3 to equal 4
      + expected - actual
      
      -3
      +4
      
      at r (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:9576:21)
      at node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:251:8
      at p (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:1410:10)
      at c (node_modules/@esm-bundle/chai/node_modules/.pnpm/chai@4.3.4/node_modules/chai/chai.js:7884:30)
      at src/replicache.test.ts:2115:35
```

**Comment by phritz** [comment]
It seems to be failing every time, so maybe turned from flaky to just plain broken (something time/date related?). I'll look in a sec.

**Comment by arv** [comment]
I'll look...

Passes locally for me so might need to do some "remote" testing

**Comment by arv** [comment]
There is some complications here.
- We are using fake timers so we can control the connection loop parameters
- IDB takes some time and not everything is reported using promises (need to fix that)

I used to have "everything" return promises but I was convinced that it was not needed for real code and it made things more complicated than needed.

I'll see if I can make some test specific changes so that we can correctly wait for things.

**Comment by phritz** [comment]
Thank you.
