### ISSUE TITLE
Recursion / infinite loop bug in "delete"

### ISSUE THREAD

**Issue by tmcw** [rocicorp/replicache#985]
Encountering the below in prod:

```
RangeError: Maximum call stack size exceeded
  at ? (./node_modules/replicache/out/replicache.mjs:1:49086)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
  at delete(./node_modules/replicache/out/replicache.mjs:1:49078)
  at ? (./node_modules/replicache/out/replicache.mjs:1:49188)
  at Array.forEach(<anonymous>)
```

It looks like there's some recursive code that isn't finding an end condition here.

**Comment by aboodman** [comment]
Thank you for the report. This looks concerning. @arv is going to look into it soon.

**Comment by arv** [comment]
@tmcw Which version is this?

**Comment by arv** [comment]
Assuming `v10.0.0-beta.0` I get:

```sh
npx stacktracify out/replicache.mjs.map
```

```
RangeError: Maximum call stack size exceeded
    at  (../src/dag/lazy-store.ts:489:34)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
    at  (../src/dag/lazy-store.ts:489:26)
    at  (../src/dag/lazy-store.ts:498:15)
    at Array.forEach
```

**Comment by arv** [comment]
The only way I think this can happen based on looking at the code is that a chunk is referencing itself. Something that should never happen.

@tmcw I'm going to add some asserts and attach a tarball here that you can try

**Comment by arv** [comment]
Attached is a new build with asserts as well as the sourcemap for that build.

[replicache-10.0.0-beta.0.tgz.zip](https://github.com/rocicorp/replicache/files/8570504/replicache-10.0.0-beta.0.tgz.zip)
[replicache.mjs.map.zip](https://github.com/rocicorp/replicache/files/8570516/replicache.mjs.map.zip)

**Comment by arv** [comment]
Fixed
